import { RoadmapItemInterface } from '../roadmap-item/roadmap-item.interface';

export const roadmapItemList: RoadmapItemInterface[] = [
  {
    level: 1,
    status: 'knowledgeAbsorbed',
    text: 'HTML',
    textVersion: 5,
    depthMeter: 52,
    child: {
      id: '3a526d02e84c480f9716a037e380ade4',
      isVisible: true,
      itemList: [
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'Semantic markup',
          hrefTitle: 'Semantic markup',
          href: 'https://developer.mozilla.org/en-US/docs/Web/HTML/Element',
          depthMeter: 0,
          gaEvent: 'htmlSemanticMarkup',
        },
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'Responsive images',
          hrefTitle: 'Responsive images',
          href: 'https://developers.google.com/web/fundamentals/design-and-ux/responsive/images',
          depthMeter: 0,
          gaEvent: 'htmlResponsiveImages',
        },
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'Conventions and best practices',
          hrefTitle: 'Conventions and best practices',
          href: 'https://github.com/hail2u/html-best-practices',
          depthMeter: 0,
          gaEvent: 'htmlConventionsAndBestPractices',
        },
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'SEO - Search engine optimization',
          hrefTitle: 'SEO - Search engine optimization',
          href: 'https://developers.google.com/search/docs',
          depthMeter: 0,
          gaEvent: 'htmlSEO',
        },
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'Accessibility',
          hrefTitle: 'Accessibility',
          href: 'https://www.smashingmagazine.com/2021/03/complete-guide-accessible-front-end-components/',
          depthMeter: 0,
          gaEvent: 'htmlAccessibility',
        },
      ],
    },
  },
  {
    level: 1,
    status: 'knowledgeAbsorbed',
    text: 'CSS',
    textVersion: 3,
    depthMeter: 52,
    child: {
      id: '098ea49e775646a2bb8323c7131da1ec',
      isVisible: false,
      itemList: [
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'Box model',
          hrefTitle: 'Box model',
          href: 'https://www.geeksforgeeks.org/css-box-model/',
          depthMeter: 52,
          gaEvent: 'cssBoxModel',
        },
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'Specificity',
          hrefTitle: 'Specificity',
          href: 'https://specifishity.com/',
          depthMeter: 52,
          gaEvent: 'cssSpecificity',
        },
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'Responsive web design based on media queries',
          hrefTitle: 'Responsive web design based on media queries',
          href: 'https://torquemag.io/2021/08/media-queries-guide/',
          depthMeter: 52,
          gaEvent: 'cssResponsiveWebDesign',
        },
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'Layouts',
          depthMeter: 52,
          gaEvent: 'cssLayouts',
          child: {
            id: 'd42cd4cca3264aa79a3de12b5d27c67b',
            isVisible: false,
            itemList: [
              {
                level: 3,
                status: 'knowledgeAbsorbed',
                text: 'Flexbox',
                hrefTitle: 'Flexbox',
                href: 'https://css-tricks.com/snippets/css/a-guide-to-flexbox/',
                depthMeter: 52,
                gaEvent: 'cssLayoutsFlexbox',
              },
              {
                level: 3,
                status: 'knowledgeNeedToGain',
                text: 'Grid',
                hrefTitle: 'Grid',
                href: 'https://css-tricks.com/snippets/css/complete-guide-grid/',
                depthMeter: 52,
                gaEvent: 'cssLayoutsGrid',
              },
            ],
          },
        },
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'Transitions and animations',
          hrefTitle: 'Transitions and animations',
          href: 'https://blog.hubspot.com/website/css-transition-vs-animation',
          depthMeter: 52,
          gaEvent: 'cssTransitionsAndAnimations',
        },
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'Methodologies',
          depthMeter: 52,
          child: {
            id: '29d35565a12b4e70b210b21c8d435ef7',
            isVisible: false,
            itemList: [
              {
                level: 3,
                status: 'knowledgeAbsorbed',
                text: 'BEM - Block, element and modifier',
                hrefTitle: 'BEM - Block, element and modifier',
                href: 'http://getbem.com/introduction/',
                depthMeter: 52,
                gaEvent: 'cssMethodologiesBEM',
              },
            ],
          },
        },
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'Preprocessors',
          depthMeter: 52,
          child: {
            id: '2076ff5a6ea04117a01c63c08539b800',
            isVisible: false,
            itemList: [
              {
                level: 3,
                status: 'knowledgeAbsorbed',
                text: 'Sass - Syntactically awesome style sheets',
                hrefTitle: 'Sass - Syntactically awesome style sheets',
                href: 'https://sass-lang.com/',
                depthMeter: 52,
                gaEvent: 'cssPreprocessorsSass',
              },
            ],
          },
        },
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'Frameworks',
          depthMeter: 52,
          child: {
            id: '7cc086a4837246d0af77f9f8f333f9f8',
            isVisible: false,
            itemList: [
              {
                level: 3,
                status: 'knowledgeAbsorbed',
                text: 'Based on CSS first',
                depthMeter: 52,
                child: {
                  id: 'c11aae5a09824883a9604295185e9d2b',
                  isVisible: false,
                  itemList: [
                    {
                      level: 4,
                      status: 'knowledgeAbsorbed',
                      text: 'Foundation',
                      hrefTitle: 'Foundation',
                      href: 'https://get.foundation/',
                      depthMeter: 52,
                      gaEvent: 'cssFrameworksFoundation',
                    },
                    {
                      level: 4,
                      status: 'knowledgeAbsorbed',
                      text: 'Bootstrap',
                      hrefTitle: 'Bootstrap',
                      href: 'https://getbootstrap.com/',
                      depthMeter: 52,
                      gaEvent: 'cssFrameworksBootstrap',
                    },
                    {
                      level: 4,
                      status: 'knowledgeAbsorbed',
                      text: 'Tailwind',
                      hrefTitle: 'Tailwind',
                      href: 'https://tailwindcss.com/',
                      depthMeter: 52,
                      gaEvent: 'cssFrameworksTailwind',
                    },
                  ],
                },
              },
              {
                level: 3,
                status: 'knowledgeAbsorbed',
                text: 'JavaScript based',
                depthMeter: 52,
                child: {
                  id: 'd33732acad18448cb1ad327b067e34d3',
                  isVisible: false,
                  itemList: [
                    {
                      level: 4,
                      status: 'knowledgeAbsorbed',
                      text: 'Chakra UI',
                      hrefTitle: 'Chakra UI',
                      href: 'https://chakra-ui.com/',
                      depthMeter: 52,
                      gaEvent: 'cssFrameworksChakraUI',
                    },
                  ],
                },
              },
            ],
          },
        },
      ],
    },
  },
  {
    level: 1,
    status: 'knowledgeAbsorbed',
    text: 'JavaScript',
    textVersion: 'ES6+',
    depthMeter: 0,
    child: {
      id: '936a6bfeb58b42e99aa32a89a543a9ca',
      isVisible: false,
      itemList: [
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'DOM - document object model - manipulation',
          hrefTitle: 'DOM - document object model - manipulation',
          href: 'https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Manipulating_documents',
          depthMeter: 0,
          gaEvent: 'javaScriptDOMmanipulation',
        },
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'Modules',
          hrefTitle: 'Modules',
          href: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules',
          depthMeter: 0,
          gaEvent: 'javaScriptModules',
        },
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'Frameworks and libraries',
          depthMeter: 0,
          child: {
            id: 'd70aa63e75a3470a8cf4869897545b9a',
            isVisible: false,
            itemList: [
              {
                level: 3,
                status: 'knowledgeAbsorbed',
                text: 'Angular',
                depthMeter: 0,
                gaEvent: 'javaScriptFrameworksAndLibrariesAngular',
                child: {
                  id: '146f1643da98499a88c5de53fcbbbf9e',
                  isVisible: false,
                  itemList: [
                    {
                      level: 4,
                      status: 'knowledgeAbsorbed',
                      text: 'Modules',
                      hrefTitle: 'Modules',
                      href: 'https://angular.io/guide/architecture-modules',
                      depthMeter: 0,
                      gaEvent: 'angularModules',
                    },
                    {
                      level: 4,
                      status: 'knowledgeAbsorbed',
                      text: 'Components',
                      hrefTitle: 'Components',
                      href: 'https://angular.io/guide/architecture-components',
                      depthMeter: 0,
                      gaEvent: 'angularComponents',
                    },
                    {
                      level: 4,
                      status: 'knowledgeAbsorbed',
                      text: 'Templates',
                      hrefTitle: 'Templates',
                      href: 'https://angular.io/guide/template-syntax',
                      depthMeter: 0,
                      gaEvent: 'angularTemplates',
                    },
                    {
                      level: 4,
                      status: 'knowledgeAbsorbed',
                      text: 'Directives',
                      hrefTitle: 'Directives',
                      href: 'https://angular.io/guide/built-in-directives',
                      depthMeter: 0,
                      gaEvent: 'angularDirectives',
                    },
                    {
                      level: 4,
                      status: 'knowledgeAbsorbed',
                      text: 'Services',
                      hrefTitle: 'Services',
                      href: 'https://angular.io/guide/architecture-services',
                      depthMeter: 0,
                      gaEvent: 'angularServices',
                    },
                    {
                      level: 4,
                      status: 'knowledgeAbsorbed',
                      text: 'Dependency injection',
                      hrefTitle: 'Dependency injection',
                      href: 'https://angular.io/guide/dependency-injection',
                      depthMeter: 0,
                      gaEvent: 'angularDependencyInjection',
                    },
                    {
                      level: 4,
                      status: 'knowledgeAbsorbed',
                      text: 'Routing',
                      hrefTitle: 'Routing',
                      href: 'https://angular.io/guide/routing-overview',
                      depthMeter: 0,
                      gaEvent: 'angularRouting',
                    },
                    {
                      level: 4,
                      status: 'knowledgeAbsorbed',
                      text: 'Reactive forms',
                      hrefTitle: 'Reactive forms',
                      href: 'https://angular.io/guide/reactive-forms',
                      depthMeter: 0,
                      gaEvent: 'angularReactiveForms',
                    },
                    {
                      level: 4,
                      status: 'knowledgeAbsorbed',
                      text: 'HTTP client',
                      hrefTitle: 'HTTP client',
                      href: 'https://angular.io/guide/http',
                      depthMeter: 0,
                      gaEvent: 'angularHTTPclient',
                    },
                    {
                      level: 4,
                      status: 'knowledgeAbsorbed',
                      text: 'Testing',
                      hrefTitle: 'Testing',
                      href: 'https://angular.io/guide/testing',
                      depthMeter: 0,
                      gaEvent: 'angularTesting',
                    },
                    {
                      level: 4,
                      status: 'knowledgeAbsorbed',
                      text: 'Internationalization',
                      hrefTitle: 'Internationalization',
                      href: 'https://angular.io/guide/i18n-overview',
                      depthMeter: 0,
                      gaEvent: 'angularInternationalization',
                    },
                    {
                      level: 4,
                      status: 'knowledgeNeedToGain',
                      text: 'Service workers and PWA',
                      hrefTitle: 'Service workers and PWA',
                      href: 'https://angular.io/guide/service-worker-intro',
                      depthMeter: 0,
                      gaEvent: 'angularServiceWorkersAndPWA',
                    },
                    {
                      level: 4,
                      status: 'knowledgeNeedToGain',
                      text: 'Web workers',
                      hrefTitle: 'Web workers',
                      href: 'https://angular.io/guide/web-worker',
                      depthMeter: 0,
                      gaEvent: 'angularWebWorkers',
                    },
                    {
                      level: 4,
                      status: 'knowledgeNeedToGain',
                      text: 'SSR - Server-side rendering',
                      hrefTitle: 'SSR - Server-side rendering',
                      href: 'https://angular.io/guide/universal',
                      depthMeter: 0,
                      gaEvent: 'angularSSR',
                    },
                    {
                      level: 4,
                      status: 'knowledgeNeedToGain',
                      text: 'Prerendering',
                      hrefTitle: 'Prerendering',
                      href: 'https://angular.io/guide/prerendering',
                      depthMeter: 0,
                      gaEvent: 'angularPrerendering',
                    },
                    {
                      level: 4,
                      status: 'knowledgeAbsorbed',
                      text: 'CLI - Command-line interface',
                      hrefTitle: 'CLI - Command-line interface',
                      href: 'https://angular.io/cli',
                      depthMeter: 0,
                      gaEvent: 'angularCLI',
                    },
                    {
                      level: 4,
                      status: 'knowledgeAbsorbed',
                      text: 'Libraries',
                      depthMeter: 0,
                      child: {
                        id: '64f455866ee34efa988c97c117f24b69',
                        isVisible: false,
                        itemList: [
                          {
                            level: 5,
                            status: 'knowledgeNeedToGain',
                            text: 'NgRx - Reactive State for Angular',
                            hrefTitle: 'NgRx - Reactive State for Angular',
                            href: 'https://ngrx.io/',
                            depthMeter: 0,
                            gaEvent: 'angularLibrariesNgRx',
                          },
                        ],
                      },
                    },
                  ],
                },
              },
              {
                level: 3,
                status: 'knowledgeAbsorbed',
                text: 'React',
                hrefTitle: 'React (the basics)',
                href: 'https://reactjs.org/',
                textNote: '(I have acquired basics)',
                depthMeter: 0,
                gaEvent: 'javaScriptFrameworksAndLibrariesReact',
              },
              {
                level: 3,
                status: 'knowledgeAbsorbed',
                text: 'Vue.js and Vuex',
                depthMeter: 0,
                gaEvent: 'javaScriptFrameworksAndLibrariesVueJsAndVueX',
                child: {
                  id: 'df9e973f7f04413a896e42171efbdc97',
                  isVisible: false,
                  itemList: [
                    {
                      level: 4,
                      status: 'knowledgeAbsorbed',
                      text: 'Vue.js',
                      hrefTitle: 'Vue.js',
                      href: 'https://vuex.vuejs.org/',
                      textNote: '(I have acquired basics)',
                      depthMeter: 0,
                      gaEvent: 'javaScriptFrameworksAndLibrariesVueJs',
                    },
                    {
                      level: 4,
                      status: 'knowledgeAbsorbed',
                      text: 'Vuex',
                      hrefTitle: 'Vuex',
                      href: 'https://vuex.vuejs.org/',
                      depthMeter: 0,
                      gaEvent: 'javaScriptFrameworksAndLibrariesVuex',
                    },
                  ],
                },
              },
              {
                level: 3,
                status: 'knowledgeNeedToGain',
                text: 'Svelte',
                hrefTitle: 'Svelte',
                href: 'https://svelte.dev/',
                depthMeter: 0,
                gaEvent: 'javaScriptFrameworksAndLibrariesSvelte',
              },
              {
                level: 3,
                status: 'knowledgeAbsorbed',
                text: 'RxJS - Reactive Extensions Library for JavaScript',
                hrefTitle: 'RxJS - Reactive Extensions Library for JavaScript',
                href: 'https://rxjs.dev/',
                depthMeter: 0,
                gaEvent: 'javaScriptFrameworksAndLibrariesRxJS',
              },
            ],
          },
        },
      ],
    },
  },
  {
    level: 1,
    status: 'knowledgeAbsorbed',
    text: 'Version control systems',
    depthMeter: 0,
    child: {
      id: '102f129b552b41acbc999c7ccec8ffca',
      isVisible: false,
      itemList: [
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'Git - Global Information Tracker',
          hrefTitle: 'Git - Global Information Tracker',
          href: 'https://git-scm.com/',
          depthMeter: 0,
          gaEvent: 'versionControlSystemsGit',
        },
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'Code hosting platforms',
          depthMeter: 0,
          child: {
            id: '512e3acac5024258915cec0e4b96f5b4',
            isVisible: false,
            itemList: [
              {
                level: 3,
                status: 'knowledgeAbsorbed',
                text: 'GitHub',
                hrefTitle: 'GitHub',
                href: 'https://github.com/',
                depthMeter: 0,
                gaEvent: 'versionControlSystemsGitHub',
              },
              {
                level: 3,
                status: 'knowledgeAbsorbed',
                text: 'GitLab',
                hrefTitle: 'GitLab',
                href: 'https://about.gitlab.com/',
                depthMeter: 0,
                gaEvent: 'versionControlSystemsGitLab',
              },
              {
                level: 3,
                status: 'knowledgeAbsorbed',
                text: 'Bitbucket',
                hrefTitle: 'Bitbucket',
                href: 'https://bitbucket.org/',
                depthMeter: 0,
                gaEvent: 'versionControlSystemsBitbucket',
              },
            ],
          },
        },
      ],
    },
  },
  {
    level: 1,
    status: 'knowledgeAbsorbed',
    text: 'Package managers',
    depthMeter: 0,
    child: {
      id: '89fdcac6bb6d4b43a356753225206893',
      isVisible: false,
      itemList: [
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'yarn',
          hrefTitle: 'yarn',
          href: 'https://yarnpkg.com/',
          depthMeter: 0,
          gaEvent: 'packageManagersYarn',
        },
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'npm',
          hrefTitle: 'npm',
          href: 'https://www.npmjs.com/',
          depthMeter: 0,
          gaEvent: 'packageManagersNpm',
        },
      ],
    },
  },
  {
    level: 1,
    status: 'knowledgeAbsorbed',
    text: 'Web security',
    depthMeter: 0,
    child: {
      id: '11eb7f1ff6384be78b587b244a2c567d',
      isVisible: false,
      itemList: [
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'HTTPS - Hypertext transfer protocol secure',
          hrefTitle: 'HTTPS - Hypertext transfer protocol secure',
          href: 'https://www.cloudflare.com/en-gb/learning/ssl/why-is-http-not-secure/',
          depthMeter: 0,
          gaEvent: 'webSecurityHTTPS',
        },
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'CORS - Cross-origin resource sharing',
          hrefTitle: 'CORS - Cross-origin resource sharing',
          href: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS',
          depthMeter: 0,
          gaEvent: 'webSecurityCORS',
        },
        // TODO: figure out
        // {
        //   level: 2,
        //   status: 'knowledgeAbsorbed',
        //   hrefTitle: 'CSP - Content security policy',
        //   href: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP',
        //   text: 'CSP - Content security policy',
        //   gaEvent: 'webSecurityCSP',
        // },
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'Top 10 OWASP security risks',
          hrefTitle: 'Top 10 OWASP security risks',
          href: 'https://owasp.org/www-project-top-ten/',
          depthMeter: 0,
          gaEvent: 'webSecurityTop10OWASPsecurityRisks',
        },
      ],
    },
  },
  {
    level: 1,
    status: 'knowledgeAbsorbed',
    text: 'Web applications authentication and authorization',
    depthMeter: 0,
    // TODO: childList: [] e.g. openId, keycloak
  },
  {
    level: 1,
    status: 'knowledgeAbsorbed',
    text: 'Web applications testing',
    depthMeter: 0,
    child: {
      id: 'b20d1d00d5de4ce78f67c252b1399fbd',
      isVisible: false,
      itemList: [
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'Functional tests',
          depthMeter: 0,
          child: {
            id: '76396adee1f949a3abf1e2ae7b83d91f',
            isVisible: false,
            itemList: [
              {
                level: 3,
                status: 'knowledgeAbsorbed',
                text: 'Unit tests',
                hrefTitle: 'Unit tests',
                href: 'https://www.guru99.com/unit-testing-guide.html',
                depthMeter: 0,
                gaEvent: 'webApplicationsTestingUnitTest',
              },
              {
                level: 3,
                status: 'knowledgeNeedToGain',
                text: 'Integration tests',
                hrefTitle: 'Integration tests',
                href: 'https://www.guru99.com/integration-testing.html',
                depthMeter: 0,
                gaEvent: 'webApplicationsTestingIntegrationTest',
              },
            ],
          },
        },
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'Frameworks',
          depthMeter: 0,
          child: {
            id: 'cf00b9b02bf0449e8fd8977741c29cdf',
            isVisible: false,
            itemList: [
              {
                level: 3,
                status: 'knowledgeAbsorbed',
                text: 'Jasmine',
                hrefTitle: 'Jasmine',
                href: 'https://jasmine.github.io/',
                depthMeter: 0,
                gaEvent: 'webApplicationsTestingFrameworksJasmine',
              },
              {
                level: 3,
                status: 'knowledgeAbsorbed',
                text: 'Karma',
                hrefTitle: 'Karma',
                href: 'https://karma-runner.github.io/latest/index.html',
                depthMeter: 0,
                gaEvent: 'webApplicationsTestingFrameworksKarma',
              },
            ],
          },
        },
      ],
    },
  },
  {
    level: 1,
    status: 'knowledgeAbsorbed',
    text: 'Web applications versioning',
    depthMeter: 0,
    child: {
      id: '5816c0ce7f7d40d2995cea530e11e343',
      isVisible: false,
      itemList: [
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'Semantic versioning',
          hrefTitle: 'Semantic versioning',
          href: 'https://semver.org/',
          depthMeter: 0,
          gaEvent: 'webApplicationsVersioningSemanticVersioning',
        },
      ],
    },
  },
  {
    level: 1,
    status: 'knowledgeAbsorbed',
    text: 'E-commerce platforms',
    depthMeter: 0,
    child: {
      id: '6c387bd75cde4966bc09aece9fe8ae22',
      isVisible: false,
      itemList: [
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'Shopware',
          hrefTitle: 'Shopware',
          href: 'https://www.shopware.com/en/',
          depthMeter: 0,
          gaEvent: 'eCommerceShopware',
        },
        {
          level: 2,
          status: 'knowledgeNeedToGain',
          text: 'commercetools',
          hrefTitle: 'commercetools',
          href: 'https://commercetools.com/',
          depthMeter: 0,
          gaEvent: 'eCommerceCommercetools',
        },
        {
          level: 2,
          status: 'knowledgeNeedToGain',
          text: 'Pimcore',
          hrefTitle: 'Pimcore',
          href: 'https://pimcore.com/en',
          depthMeter: 0,
          gaEvent: 'eCommercePimcore',
        },
      ],
    },
  },
  {
    level: 1,
    status: 'knowledgeAbsorbed',
    text: 'Static site generators',
    depthMeter: 0,
    child: {
      id: 'b5982e1598bb41a6ab30755b0737bbe0',
      isVisible: false,
      itemList: [
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'NuxtJS',
          hrefTitle: 'NuxtJS',
          href: 'https://nuxtjs.org/',
          depthMeter: 0,
          gaEvent: 'staticSiteGeneratorsNuxtJS',
        },
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'Jekyll',
          hrefTitle: 'Jekyll',
          href: 'https://jekyllrb.com/',
          depthMeter: 0,
          gaEvent: 'staticSiteGeneratorsJekyll',
        },
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'VuePress',
          hrefTitle: 'VuePress',
          href: 'https://vuepress.vuejs.org/',
          depthMeter: 0,
          gaEvent: 'staticSiteGeneratorsVuePress',
        },
        {
          level: 2,
          status: 'knowledgeNeedToGain',
          text: 'Hugo',
          hrefTitle: 'Hugo',
          href: 'https://gohugo.io/',
          depthMeter: 0,
          gaEvent: 'staticSiteGeneratorsHugo',
        },
        {
          level: 2,
          status: 'knowledgeNeedToGain',
          text: 'Eleventy',
          hrefTitle: 'Eleventy',
          href: 'https://www.11ty.dev/',
          depthMeter: 0,
          gaEvent: 'staticSiteGeneratorsEleventy',
        },
      ],
    },
  },
  {
    level: 1,
    status: 'knowledgeAbsorbed',
    text: 'Virtualization',
    depthMeter: 0,
    child: {
      id: '46f156f2484e4ca093c250cb11d26c28',
      isVisible: false,
      itemList: [
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'Docker',
          hrefTitle: 'Docker',
          href: 'https://www.docker.com/',
          depthMeter: 0,
          gaEvent: 'virtualizationDocker',
        },
      ],
    },
  },
  {
    level: 1,
    status: 'knowledgeAbsorbed',
    text: 'And I keep learning',
    depthMeter: 0,
    child: {
      id: '5bb33e64920b4a49a6fdddef6240152a',
      isVisible: true,
      itemList: [
        {
          level: 2,
          status: 'knowledgeNeedToGain',
          text: 'What is going to be next?',
          depthMeter: 0,
        },
      ],
    },
  },
];
