import { RoadmapItemInterface } from '../roadmap-item/roadmap-item.interface';

export const roadmapItemList: RoadmapItemInterface[] = [
  {
    level: 1,
    isVisible: true,
    status: 'knowledgeAbsorbed',
    text: 'Coding and programming languages',
    depthMeter: 0,
    gaEvent: 'codingAndProgrammingLanguages',
    child: {
      isVisible: true,
      itemList: [
        {
          level: 2,
          isVisible: false,
          status: 'knowledgeAbsorbed',
          text: 'HTML',
          textVersion: '5',
          depthMeter: 0,
          gaEvent: 'codingAndProgrammingLanguagesHtml',
          child: {
            isVisible: false,
            itemList: [
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Semantic markup',
                hrefTitle: 'Semantic markup',
                href: 'https://developer.mozilla.org/en-US/docs/Web/HTML/Element',
                depthMeter: 0,
                gaEvent: 'codingAndProgrammingLanguagesHtmlSemanticMarkup',
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Responsive images',
                hrefTitle: 'Responsive images',
                href: 'https://developers.google.com/web/fundamentals/design-and-ux/responsive/images',
                depthMeter: 0,
                gaEvent: 'codingAndProgrammingLanguagesHtmlResponsiveImages',
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Input types',
                hrefTitle: 'Input types',
                href: 'https://developer.mozilla.org/en-US/docs/Learn/Forms/HTML5_input_types',
                depthMeter: 0,
                gaEvent: 'codingAndProgrammingLanguagesHtmlInputTypes',
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'SEO - Search engine optimization',
                hrefTitle: 'SEO - Search engine optimization',
                href: 'https://developers.google.com/search/docs',
                depthMeter: 0,
                gaEvent:
                  'codingAndProgrammingLanguagesHtmlSeoSearchEngineOptimization',
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Accessibility',
                hrefTitle: 'Accessibility',
                href: 'https://www.smashingmagazine.com/2021/03/complete-guide-accessible-front-end-components/',
                depthMeter: 0,
                gaEvent: 'codingAndProgrammingLanguagesHtmlAccessibility',
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Conventions and best practices',
                hrefTitle: 'Conventions and best practices',
                href: 'https://github.com/hail2u/html-best-practices',
                depthMeter: 0,
                gaEvent:
                  'codingAndProgrammingLanguagesHtmlConventionsAndBestPractices',
              },
            ],
          },
        },
        {
          level: 2,
          isVisible: false,
          status: 'knowledgeAbsorbed',
          text: 'CSS',
          textVersion: '3',
          depthMeter: 0,
          gaEvent: 'codingAndProgrammingLanguagesCss',
          child: {
            isVisible: false,
            itemList: [
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Specificity',
                hrefTitle: 'Specificity',
                href: 'https://specifishity.com/',
                depthMeter: 0,
                gaEvent: 'codingAndProgrammingLanguagesCssSpecificity',
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Responsive web design based on media queries',
                hrefTitle: 'Responsive web design based on media queries',
                href: 'https://torquemag.io/2021/08/media-queries-guide/',
                depthMeter: 0,
                gaEvent:
                  'codingAndProgrammingLanguagesCssResponsiveWebDesignBasedOnMediaQueries',
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Layouts',
                depthMeter: 0,
                gaEvent: 'codingAndProgrammingLanguagesCssLayouts',
                child: {
                  isVisible: false,
                  itemList: [
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Box model',
                      hrefTitle: 'Box model',
                      href: 'https://www.geeksforgeeks.org/css-box-model/',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesCssLayoutsBoxModel',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Positioning',
                      hrefTitle: 'Positioning',
                      href: 'https://css-tricks.com/almanac/properties/p/position/',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesCssLayoutsPositioning',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Displaying',
                      hrefTitle: 'Displaying',
                      href: 'https://www.geeksforgeeks.org/css-display-property/',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesCssLayoutsDisplaying',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Flexbox',
                      hrefTitle: 'Flexbox',
                      href: 'https://css-tricks.com/snippets/css/a-guide-to-flexbox/',
                      depthMeter: 0,
                      gaEvent: 'codingAndProgrammingLanguagesCssLayoutsFlexbox',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeNeedToGain',
                      text: 'Grid',
                      hrefTitle: 'Grid',
                      href: 'https://css-tricks.com/snippets/css/complete-guide-grid/',
                      depthMeter: 0,
                      gaEvent: 'codingAndProgrammingLanguagesCssLayoutsGrid',
                    },
                  ],
                },
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Transitions and animations',
                hrefTitle: 'Transitions and animations',
                href: 'https://blog.hubspot.com/website/css-transition-vs-animation',
                depthMeter: 0,
                gaEvent:
                  'codingAndProgrammingLanguagesCssTransitionsAndAnimations',
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Methodologies',
                depthMeter: 0,
                gaEvent: 'codingAndProgrammingLanguagesCssMethodologies',
                child: {
                  isVisible: false,
                  itemList: [
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'BEM - Block, element and modifier',
                      hrefTitle: 'BEM - Block, element and modifier',
                      href: 'http://getbem.com/introduction/',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesCssMethodologiesBemBlockElementAndModifier',
                    },
                  ],
                },
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Preprocessors',
                depthMeter: 0,
                gaEvent: 'codingAndProgrammingLanguagesCssPreprocessors',
                child: {
                  isVisible: false,
                  itemList: [
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Sass - Syntactically awesome style sheets',
                      hrefTitle: 'Sass - Syntactically awesome style sheets',
                      href: 'https://sass-lang.com/',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesCssPreprocessorsSassSyntacticallyAwesomeStyleSheets',
                    },
                  ],
                },
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Frameworks',
                depthMeter: 0,
                gaEvent: 'codingAndProgrammingLanguagesCssFrameworks',
                child: {
                  isVisible: false,
                  itemList: [
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Based on CSS first',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesCssFrameworksBasedOnCssFirst',
                      child: {
                        isVisible: false,
                        itemList: [
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'Foundation',
                            hrefTitle: 'Foundation',
                            href: 'https://get.foundation/',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesCssFrameworksBasedOnCssFirstFoundation',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'Bootstrap',
                            hrefTitle: 'Bootstrap',
                            href: 'https://getbootstrap.com/',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesCssFrameworksBasedOnCssFirstBootstrap',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'Tailwind',
                            hrefTitle: 'Tailwind',
                            href: 'https://tailwindcss.com/',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesCssFrameworksBasedOnCssFirstTailwind',
                          },
                        ],
                      },
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'JavaScript based',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesCssFrameworksJavaScriptBased',
                      child: {
                        isVisible: false,
                        itemList: [
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'Chakra UI',
                            hrefTitle: 'Chakra UI',
                            href: 'https://chakra-ui.com/',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesCssFrameworksJavaScriptBasedChakraUi',
                          },
                        ],
                      },
                    },
                  ],
                },
              },
            ],
          },
        },
        {
          level: 2,
          isVisible: false,
          status: 'knowledgeAbsorbed',
          text: 'JavaScript',
          textVersion: 'ES6+',
          depthMeter: 0,
          gaEvent: 'codingAndProgrammingLanguagesJavaScript',
          child: {
            isVisible: false,
            itemList: [
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Constructs and syntax',
                depthMeter: 0,
                gaEvent:
                  'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntax',
                child: {
                  isVisible: false,
                  itemList: [
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'DOM - document object model - manipulation',
                      hrefTitle: 'DOM - document object model - manipulation',
                      href: 'https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Manipulating_documents',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxDomDocumentObjectModelManipulation',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Grammar and types',
                      hrefTitle: 'Grammar and types',
                      href: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_Types',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxGrammarAndTypes',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Truthy and falsy',
                      hrefTitle: 'Truthy and falsy',
                      href: 'https://www.sitepoint.com/javascript-truthy-falsy/',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxTruthyAndFalsy',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Conditionals',
                      hrefTitle: 'Conditionals',
                      href: 'https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/conditionals',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxConditionals',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Control flow and error handling',
                      hrefTitle: 'Control flow and error handling',
                      href: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Control_flow_and_error_handling',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxControlFlowAndErrorHandling',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Loops and iteration',
                      hrefTitle: 'Loops and iteration',
                      href: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Loops_and_iteration',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxLoopsAndIteration',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Functions',
                      hrefTitle: 'Functions',
                      href: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxFunctions',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Expressions and operators',
                      hrefTitle: 'Expressions and operators',
                      href: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Expressions_and_Operators',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxExpressionsAndOperators',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Numbers and dates',
                      hrefTitle: 'Numbers and dates',
                      href: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Numbers_and_dates',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxNumbersAndDates',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Text formatting',
                      hrefTitle: 'Text formatting',
                      href: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Text_formatting',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxTextFormatting',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Regular expressions',
                      hrefTitle: 'Regular expressions',
                      href: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxRegularExpressions',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Events',
                      hrefTitle: 'Events',
                      href: 'https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxEvents',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Indexed collections',
                      hrefTitle: 'Indexed collections',
                      href: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Indexed_collections',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxIndexedCollections',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Working with objects',
                      hrefTitle: 'Working with objects',
                      href: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxWorkingWithObjects',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Web components',
                      hrefTitle: 'Web components',
                      href: 'https://www.webcomponents.org/introduction',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxWebComponents',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'XMLHttpRequest',
                      hrefTitle: 'XMLHttpRequest',
                      href: 'https://javascript.info/xmlhttprequest',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxXmlHttpRequest',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Fetch API',
                      hrefTitle: 'Fetch API',
                      href: 'https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Fetching_data',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxFetchApi',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Client-side storage',
                      hrefTitle: 'Client-side storage',
                      href: 'https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxClientSideStorage',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeNeedToGain',
                      text: 'Web workers',
                      hrefTitle: 'Web workers',
                      href: 'https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Introducing_workers',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxWebWorkers',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeNeedToGain',
                      text: 'Iterators and generators',
                      hrefTitle: 'Iterators and generators',
                      href: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_generators',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxIteratorsAndGenerators',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeNeedToGain',
                      text: 'Meta programming',
                      hrefTitle: 'Meta programming',
                      href: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Meta_programming',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxMetaProgramming',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'ES6 (ECMAScript 2015)',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxEs6EcmaScript2015',
                      child: {
                        isVisible: false,
                        itemList: [
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'Modules',
                            hrefTitle: 'Modules',
                            href: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxEs6EcmaScript2015Modules',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'Keywords let and const',
                            hrefTitle: 'Keywords let and const',
                            href: 'https://www.boardinfinity.com/blog/top-10-features-of-es6/#1-let-and-const-keywords-',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxEs6EcmaScript2015KeywordsLetAndConst',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'Promises',
                            hrefTitle: 'Promises',
                            href: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxEs6EcmaScript2015Promises',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'Async function',
                            hrefTitle: 'Async function',
                            href: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxEs6EcmaScript2015AsyncFunction',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'Template literals',
                            hrefTitle: 'Template literals',
                            href: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxEs6EcmaScript2015TemplateLiterals',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'Keyed collections',
                            hrefTitle: 'Keyed collections',
                            href: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Keyed_collections',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxEs6EcmaScript2015KeyedCollections',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'Classes',
                            hrefTitle: 'Classes',
                            href: 'https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Classes_in_JavaScript',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxEs6EcmaScript2015Classes',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'Destructuring, spread and rest parameter',
                            hrefTitle:
                              'Destructuring, spread and rest parameter',
                            href: 'https://www.freecodecamp.org/news/javascript-object-destructuring-spread-operator-rest-parameter/',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxEs6EcmaScript2015DestructuringSpreadAndRestParameter',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'Arrow function',
                            hrefTitle: 'Arrow function',
                            href: 'https://www.boardinfinity.com/blog/top-10-features-of-es6/#2-arrow-functions',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxEs6EcmaScript2015ArrowFunction',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'Function default parameters',
                            hrefTitle: 'Function default parameters',
                            href: 'https://www.boardinfinity.com/blog/top-10-features-of-es6/#4-default-parameters',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxEs6EcmaScript2015FunctionDefaultParameters',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'Enhanced object literals',
                            hrefTitle: 'Enhanced object literals',
                            href: 'https://www.boardinfinity.com/blog/top-10-features-of-es6/#7-enhanced-object-literals',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptConstructsAndSyntaxEs6EcmaScript2015EnhancedObjectLiterals',
                          },
                        ],
                      },
                    },
                  ],
                },
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Concepts',
                depthMeter: 0,
                gaEvent: 'codingAndProgrammingLanguagesJavaScriptConcepts',
                child: {
                  isVisible: false,
                  itemList: [
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Hoisting',
                      hrefTitle: 'Hoisting',
                      href: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_Types#variable_hoisting',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptConceptsHoisting',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Event bubbling',
                      hrefTitle: 'Event bubbling',
                      href: 'https://www.sitepoint.com/event-bubbling-javascript/',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptConceptsEventBubbling',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Scope',
                      hrefTitle: 'Scope',
                      href: 'https://dmitripavlutin.com/javascript-scope/',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptConceptsScope',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Prototype',
                      hrefTitle: 'Prototype',
                      href: 'https://www.tutorialsteacher.com/javascript/prototype-in-javascript',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptConceptsPrototype',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Shadow DOM',
                      hrefTitle: 'Shadow DOM',
                      href: 'https://javascript.info/shadow-dom',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptConceptsShadowDom',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Strict',
                      hrefTitle: 'Strict',
                      href: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptConceptsStrict',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Encapsulation',
                      hrefTitle: 'Encapsulation',
                      href: 'https://medium.com/javascript-scene/encapsulation-in-javascript-26be60e325b4',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptConceptsEncapsulation',
                    },
                  ],
                },
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Frameworks and libraries',
                depthMeter: 0,
                gaEvent:
                  'codingAndProgrammingLanguagesJavaScriptFrameworksAndLibraries',
                child: {
                  isVisible: false,
                  itemList: [
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Angular',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptFrameworksAndLibrariesAngular',
                      child: {
                        isVisible: false,
                        itemList: [
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'Modules',
                            hrefTitle: 'Modules',
                            href: 'https://angular.io/guide/architecture-modules',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptFrameworksAndLibrariesAngularModules',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'Components',
                            hrefTitle: 'Components',
                            href: 'https://angular.io/guide/architecture-components',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptFrameworksAndLibrariesAngularComponents',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'Templates',
                            hrefTitle: 'Templates',
                            href: 'https://angular.io/guide/template-syntax',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptFrameworksAndLibrariesAngularTemplates',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'Directives',
                            hrefTitle: 'Directives',
                            href: 'https://angular.io/guide/built-in-directives',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptFrameworksAndLibrariesAngularDirectives',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'Pipes',
                            hrefTitle: 'Pipes',
                            href: 'https://angular.io/guide/pipes',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptFrameworksAndLibrariesAngularPipes',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'Services',
                            hrefTitle: 'Services',
                            href: 'https://angular.io/guide/architecture-services',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptFrameworksAndLibrariesAngularServices',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'Dependency injection',
                            hrefTitle: 'Dependency injection',
                            href: 'https://angular.io/guide/dependency-injection',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptFrameworksAndLibrariesAngularDependencyInjection',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'Routing',
                            hrefTitle: 'Routing',
                            href: 'https://angular.io/guide/routing-overview',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptFrameworksAndLibrariesAngularRouting',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'Reactive forms',
                            hrefTitle: 'Reactive forms',
                            href: 'https://angular.io/guide/reactive-forms',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptFrameworksAndLibrariesAngularReactiveForms',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'HTTP client',
                            hrefTitle: 'HTTP client',
                            href: 'https://angular.io/guide/http',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptFrameworksAndLibrariesAngularHttpClient',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'Testing',
                            hrefTitle: 'Testing',
                            href: 'https://angular.io/guide/testing',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptFrameworksAndLibrariesAngularTesting',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'I18n',
                            hrefTitle: 'I18n',
                            href: 'https://angular.io/guide/i18n-overview',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptFrameworksAndLibrariesAngularI18n',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeNeedToGain',
                            text: 'Service workers and PWA',
                            hrefTitle: 'Service workers and PWA',
                            href: 'https://angular.io/guide/service-worker-intro',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptFrameworksAndLibrariesAngularServiceWorkersAndPwa',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeNeedToGain',
                            text: 'Web workers',
                            hrefTitle: 'Web workers',
                            href: 'https://angular.io/guide/web-worker',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptFrameworksAndLibrariesAngularWebWorkers',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeNeedToGain',
                            text: 'SSR - Server-side rendering',
                            hrefTitle: 'SSR - Server-side rendering',
                            href: 'https://angular.io/guide/universal',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptFrameworksAndLibrariesAngularSsrServerSideRendering',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeNeedToGain',
                            text: 'Prerendering',
                            hrefTitle: 'Prerendering',
                            href: 'https://angular.io/guide/prerendering',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptFrameworksAndLibrariesAngularPrerendering',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeNeedToGain',
                            text: 'View encapsulation',
                            hrefTitle: 'View encapsulation',
                            href: 'https://angular.io/guide/view-encapsulation',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptFrameworksAndLibrariesAngularViewEncapsulation',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'CLI - Command-line interface',
                            hrefTitle: 'CLI - Command-line interface',
                            href: 'https://angular.io/cli',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptFrameworksAndLibrariesAngularCliCommandLineInterface',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'Libraries',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptFrameworksAndLibrariesAngularLibraries',
                            child: {
                              isVisible: false,
                              itemList: [
                                {
                                  level: 6,
                                  isVisible: false,
                                  status: 'knowledgeAbsorbed',
                                  text: 'NgRx - Reactive state for Angular',
                                  hrefTitle:
                                    'NgRx - Reactive state for Angular',
                                  href: 'https://ngrx.io/',
                                  depthMeter: 0,
                                  gaEvent:
                                    'codingAndProgrammingLanguagesJavaScriptFrameworksAndLibrariesAngularLibrariesNgRxReactiveStateForAngular',
                                },
                              ],
                            },
                          },
                        ],
                      },
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'React',
                      textNote: '(I have acquired foundations)',
                      hrefTitle: 'React',
                      href: 'https://reactjs.org/',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptFrameworksAndLibrariesReact',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Vue.js and Vuex',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptFrameworksAndLibrariesVueJsAndVuex',
                      child: {
                        isVisible: false,
                        itemList: [
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'Vue.js',
                            textNote: '(I have acquired foundations)',
                            hrefTitle: 'Vue.js',
                            href: 'https://vuejs.org/',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptFrameworksAndLibrariesVueJsAndVuexVueJs',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'Vuex',
                            textNote: '(I have acquired foundations)',
                            hrefTitle: 'Vuex',
                            href: 'https://vuex.vuejs.org/',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptFrameworksAndLibrariesVueJsAndVuexVuex',
                          },
                        ],
                      },
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeNeedToGain',
                      text: 'Svelte',
                      hrefTitle: 'Svelte',
                      href: 'https://svelte.dev/',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptFrameworksAndLibrariesSvetle',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'RxJS - Reactive extensions library for JavaScript',
                      hrefTitle:
                        'RxJS - Reactive extensions library for JavaScript',
                      href: 'https://rxjs.dev/',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptFrameworksAndLibrariesRxJsReactiveExtensionsLibraryForJavaScript',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Node.js frameworks',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptFrameworksAndLibrariesNodeJsFrameworks',
                      child: {
                        isVisible: false,
                        itemList: [
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'Nest.js',
                            hrefTitle: 'Nest.js',
                            href: 'https://nestjs.com/',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptFrameworksAndLibrariesNodeJsFrameworksNestJs',
                          },
                          {
                            level: 5,
                            isVisible: false,
                            status: 'knowledgeAbsorbed',
                            text: 'Express.js',
                            hrefTitle: 'Express.js',
                            href: 'https://expressjs.com/',
                            depthMeter: 0,
                            gaEvent:
                              'codingAndProgrammingLanguagesJavaScriptFrameworksAndLibrariesNodeJsFrameworksExpressJs',
                          },
                        ],
                      },
                    },
                  ],
                },
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Tools',
                depthMeter: 0,
                gaEvent: 'codingAndProgrammingLanguagesJavaScriptTools',
                child: {
                  isVisible: false,
                  itemList: [
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Babel - JavaScript compiler',
                      hrefTitle: 'Babel - JavaScript compiler',
                      href: 'https://babeljs.io/',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptToolsBabelJavaScriptCompiler',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Webpack - module bundler',
                      hrefTitle: 'Webpack - module bundler',
                      href: 'https://webpack.js.org/',
                      depthMeter: 0,
                      gaEvent:
                        'codingAndProgrammingLanguagesJavaScriptToolsWebpackModuleBundler',
                    },
                  ],
                },
              },
            ],
          },
        },
        {
          level: 2,
          isVisible: false,
          status: 'knowledgeAbsorbed',
          text: 'TypeScript',
          depthMeter: 0,
          gaEvent: 'codingAndProgrammingLanguagesTypeScript',
          child: {
            isVisible: false,
            itemList: [
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeNeedToGain',
                text: 'Control flow analysis',
                hrefTitle: 'Control flow analysis',
                href: 'https://www.typescriptlang.org/static/TypeScript%20Control%20Flow%20Analysis-8a549253ad8470850b77c4c5c351d457.png',
                depthMeter: 0,
                gaEvent:
                  'codingAndProgrammingLanguagesTypeScriptControlFlowAnalysis',
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Types',
                hrefTitle: 'Types',
                href: 'https://www.typescriptlang.org/static/TypeScript%20Types-4cbf7b9d45dc0ec8d18c6c7a0c516114.png',
                depthMeter: 0,
                gaEvent: 'codingAndProgrammingLanguagesTypeScriptTypes',
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Interfaces',
                hrefTitle: 'Interfaces',
                href: 'https://www.typescriptlang.org/static/TypeScript%20Interfaces-34f1ad12132fb463bd1dfe5b85c5b2e6.png',
                depthMeter: 0,
                gaEvent: 'codingAndProgrammingLanguagesTypeScriptInterfaces',
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Classes',
                hrefTitle: 'Classes',
                href: 'https://www.typescriptlang.org/static/TypeScript%20Classes-83cc6f8e42ba2002d5e2c04221fa78f9.png',
                depthMeter: 0,
                gaEvent: 'codingAndProgrammingLanguagesTypeScriptClasses',
              },
            ],
          },
        },
      ],
    },
  },
  {
    level: 1,
    isVisible: true,
    status: 'knowledgeAbsorbed',
    text: 'Web applications',
    depthMeter: 0,
    gaEvent: 'webApplications',
    child: {
      isVisible: false,
      itemList: [
        {
          level: 2,
          isVisible: false,
          status: 'knowledgeAbsorbed',
          text: 'Browser cache',
          hrefTitle: 'Browser cache',
          href: 'https://www.bigcommerce.com/ecommerce-answers/what-browser-cache-and-why-it-important/',
          depthMeter: 0,
          gaEvent: 'webApplicationsBrowserCache',
        },
        {
          level: 2,
          isVisible: false,
          status: 'knowledgeAbsorbed',
          text: 'Version control systems',
          depthMeter: 0,
          gaEvent: 'webApplicationsVersionControlSystems',
          child: {
            isVisible: false,
            itemList: [
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Git - Global information tracker',
                hrefTitle: 'Git - Global information tracker',
                href: 'https://git-scm.com/',
                depthMeter: 0,
                gaEvent:
                  'webApplicationsVersionControlSystemsGitGlobalInformationTracker',
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Code hosting platforms',
                depthMeter: 0,
                gaEvent:
                  'webApplicationsVersionControlSystemsCodeHostingPlatforms',
                child: {
                  isVisible: false,
                  itemList: [
                    {
                      level: 4,
                      isVisible: true,
                      status: 'knowledgeAbsorbed',
                      text: 'Azure DevOps',
                      hrefTitle: 'Azure DevOps',
                      href: 'https://azure.microsoft.com/en-us/services/devops/#overview',
                      depthMeter: 0,
                      gaEvent:
                        'webApplicationsVersionControlSystemsCodeHostingPlatformsAzureDevOps',
                    },
                    {
                      level: 4,
                      isVisible: true,
                      status: 'knowledgeAbsorbed',
                      text: 'GitHub',
                      hrefTitle: 'GitHub',
                      href: 'https://github.com/',
                      depthMeter: 0,
                      gaEvent:
                        'webApplicationsVersionControlSystemsCodeHostingPlatformsGitHub',
                    },
                    {
                      level: 4,
                      isVisible: true,
                      status: 'knowledgeAbsorbed',
                      text: 'GitLab',
                      hrefTitle: 'GitLab',
                      href: 'https://about.gitlab.com/',
                      depthMeter: 0,
                      gaEvent:
                        'webApplicationsVersionControlSystemsCodeHostingPlatformsGitLab',
                    },
                    {
                      level: 4,
                      isVisible: true,
                      status: 'knowledgeAbsorbed',
                      text: 'Bitbucket',
                      hrefTitle: 'Bitbucket',
                      href: 'https://bitbucket.org/',
                      depthMeter: 0,
                      gaEvent:
                        'webApplicationsVersionControlSystemsCodeHostingPlatformsBitbucket',
                    },
                  ],
                },
              },
            ],
          },
        },
        {
          level: 2,
          isVisible: false,
          status: 'knowledgeAbsorbed',
          text: 'Package managers',
          depthMeter: 0,
          gaEvent: 'webApplicationsPackageManagers',
          child: {
            isVisible: false,
            itemList: [
              {
                level: 3,
                isVisible: true,
                status: 'knowledgeAbsorbed',
                text: 'yarn',
                hrefTitle: 'yarn',
                href: 'https://yarnpkg.com/',
                depthMeter: 0,
                gaEvent: 'webApplicationsPackageManagersYarn',
              },
              {
                level: 3,
                isVisible: true,
                status: 'knowledgeAbsorbed',
                text: 'npm',
                hrefTitle: 'npm',
                href: 'https://www.npmjs.com/',
                depthMeter: 0,
                gaEvent: 'webApplicationsPackageManagersNpm',
              },
            ],
          },
        },
        {
          level: 2,
          isVisible: false,
          status: 'knowledgeAbsorbed',
          text: 'Security',
          depthMeter: 0,
          gaEvent: 'webApplicationsSecurity',
          child: {
            isVisible: false,
            itemList: [
              {
                level: 3,
                isVisible: true,
                status: 'knowledgeAbsorbed',
                text: 'HTTPS - Hypertext transfer protocol secure',
                hrefTitle: 'HTTPS - Hypertext transfer protocol secure',
                href: 'https://www.cloudflare.com/en-gb/learning/ssl/why-is-http-not-secure/',
                depthMeter: 0,
                gaEvent:
                  'webApplicationsSecurityHttpsHypertextTransferProtocolSecure',
              },
              {
                level: 3,
                isVisible: true,
                status: 'knowledgeAbsorbed',
                text: 'CORS - Cross-origin resource sharing',
                hrefTitle: 'CORS - Cross-origin resource sharing',
                href: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS',
                depthMeter: 0,
                gaEvent:
                  'webApplicationsSecurityCorsCrossOriginResourceSharing',
              },
              {
                level: 3,
                isVisible: true,
                status: 'knowledgeAbsorbed',
                text: 'Top 10 OWASP security risks',
                hrefTitle: 'Top 10 OWASP security risks',
                href: 'https://owasp.org/www-project-top-ten/',
                depthMeter: 0,
                gaEvent: 'webApplicationsSecurityTop10OwaspSecurityRisks',
              },
            ],
          },
        },
        {
          level: 2,
          isVisible: false,
          status: 'knowledgeAbsorbed',
          text: 'Authentication',
          depthMeter: 0,
          gaEvent: 'webApplicationsAuthentication',
          child: {
            isVisible: false,
            itemList: [
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Basic authentication',
                hrefTitle: 'Basic authentication',
                href: 'https://www.loginradius.com/blog/engineering/everything-you-want-to-know-about-authorization-headers/#1-basic-auth',
                depthMeter: 0,
                gaEvent: 'webApplicationsAuthenticationBasicAuthentication',
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Token authentication',
                depthMeter: 0,
                gaEvent: 'webApplicationsAuthenticationTokenAuthentication',
                child: {
                  isVisible: false,
                  itemList: [
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Bearer token',
                      hrefTitle: 'Bearer token',
                      href: 'https://www.loginradius.com/blog/engineering/everything-you-want-to-know-about-authorization-headers/#2-bearer-token',
                      depthMeter: 0,
                      gaEvent:
                        'webApplicationsAuthenticationTokenAuthenticationBearerToken',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'JWT - JSON web token',
                      hrefTitle: 'JWT - JSON web token',
                      href: 'https://jwt.io/',
                      depthMeter: 0,
                      gaEvent:
                        'webApplicationsAuthenticationTokenAuthenticationJwtJsonWebToken',
                    },
                  ],
                },
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'API key authentication',
                hrefTitle: 'API key authentication',
                href: 'https://www.loginradius.com/blog/engineering/everything-you-want-to-know-about-authorization-headers/#3-api-key',
                depthMeter: 0,
                gaEvent: 'webApplicationsAuthenticationApiKeyAuthentication',
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'SSO - Single-sign on',
                hrefTitle: 'SSO - Single-sign on',
                href: 'https://www.techtarget.com/searchsecurity/definition/single-sign-on',
                depthMeter: 0,
                gaEvent: 'webApplicationsAuthenticationSingleSignOn',
              },
            ],
          },
        },
        {
          level: 2,
          isVisible: false,
          status: 'knowledgeAbsorbed',
          text: 'Authorization',
          depthMeter: 0,
          gaEvent: 'webApplicationsAuthorization',
          child: {
            isVisible: false,
            itemList: [
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'OAuth',
                textVersion: '2',
                hrefTitle: 'OAuth',
                href: 'https://oauth.net/2/',
                depthMeter: 0,
                gaEvent: 'webApplicationsAuthorizationOauth',
              },
            ]
          }
        },
        {
          level: 2,
          isVisible: false,
          status: 'knowledgeAbsorbed',
          text: 'API - Application programming interface',
          depthMeter: 0,
          gaEvent: 'webApplicationsApiApplicationProgrammingInterface',
          child: {
            isVisible: false,
            itemList: [
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'REST - Representational state transfer',
                hrefTitle: 'REST - Representational state transfer',
                href: 'https://www.codecademy.com/article/what-is-rest',
                depthMeter: 0,
                gaEvent: 'webApplicationsApiRestRepresentationalStateTransfer',
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Consuming API',
                hrefTitle: 'Consuming API',
                href: 'https://www.taniarascia.com/how-to-connect-to-an-api-with-javascript/',
                depthMeter: 0,
                gaEvent: 'webApplicationsApiConsumingApi',
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'HTTP methods',
                hrefTitle: 'HTTP methods',
                href: 'https://restfulapi.net/http-methods/',
                depthMeter: 0,
                gaEvent: 'webApplicationsApiHttpMethods',
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Status code registry',
                hrefTitle: 'Status code registry',
                href: 'https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml',
                depthMeter: 0,
                gaEvent: 'webApplicationsApiStatusCodeRegistry',
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Swagger - API documentation & design tools',
                hrefTitle: 'Swagger - API documentation & design tools',
                href: 'https://editor.swagger.io/',
                depthMeter: 0,
                gaEvent: 'webApplicationsApiSwaggerApiDocumentationDesignTools',
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Microservices',
                hrefTitle: 'Microservices',
                href: 'https://www.akana.com/resources/microservices-apis',
                depthMeter: 0,
                gaEvent: 'webApplicationsApiMicroservices',
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'GraphQL - Query language for API',
                hrefTitle: 'GraphQL - Query language for API',
                href: 'https://graphql.org/learn/',
                depthMeter: 0,
                gaEvent: 'webApplicationsApiGraphQlQueryLanguageForApi',
              },
            ],
          },
        },
        {
          level: 2,
          isVisible: false,
          status: 'knowledgeAbsorbed',
          text: 'Testing',
          depthMeter: 0,
          gaEvent: 'webApplicationsTesting',
          child: {
            isVisible: false,
            itemList: [
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Functional tests',
                depthMeter: 0,
                gaEvent: 'webApplicationsTestingFunctionalTests',
                child: {
                  isVisible: false,
                  itemList: [
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Unit tests',
                      hrefTitle: 'Unit tests',
                      href: 'https://hackr.io/blog/types-of-software-testing#1-unit-testing',
                      depthMeter: 0,
                      gaEvent: 'webApplicationsTestingFunctionalTestsUnitTests',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Integration tests',
                      hrefTitle: 'Integration tests',
                      href: 'https://hackr.io/blog/types-of-software-testing#2-integration-testing',
                      depthMeter: 0,
                      gaEvent:
                        'webApplicationsTestingFunctionalTestsIntegrationTests',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'End-to-end tests',
                      hrefTitle: 'End-to-end tests',
                      href: 'https://hackr.io/blog/types-of-software-testing#3-end-to-end-testing',
                      depthMeter: 0,
                      gaEvent:
                        'webApplicationsTestingFunctionalTestsEndToEndTests',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'User interface tests',
                      hrefTitle: 'User interface tests',
                      href: 'https://hackr.io/blog/types-of-software-testing#4-user-interface-testing',
                      depthMeter: 0,
                      gaEvent:
                        'webApplicationsTestingFunctionalTestsUserInterfaceTests',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Accessibility tests',
                      hrefTitle: 'Accessibility tests',
                      href: 'https://hackr.io/blog/types-of-software-testing#5-accessibility-testing',
                      depthMeter: 0,
                      gaEvent:
                        'webApplicationsTestingFunctionalTestsAccessibilityTests',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Browser compatibility tests',
                      hrefTitle: 'Browser compatibility tests',
                      href: 'https://hackr.io/blog/types-of-software-testing#11-browser-compatibility-testing',
                      depthMeter: 0,
                      gaEvent:
                        'webApplicationsTestingFunctionalTestsBrowserCompatibilityTests',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Performance tests',
                      hrefTitle: 'Performance tests',
                      href: 'https://hackr.io/blog/types-of-software-testing#12-performance-testing',
                      depthMeter: 0,
                      gaEvent:
                        'webApplicationsTestingFunctionalTestsPerformanceTests',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Load tests',
                      hrefTitle: 'Load tests',
                      href: 'https://hackr.io/blog/types-of-software-testing#13-load-testing',
                      depthMeter: 0,
                      gaEvent: 'webApplicationsTestingFunctionalTestsLoadTests',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'API tests',
                      hrefTitle: 'API tests',
                      href: 'https://hackr.io/blog/types-of-software-testing#17-api-testing',
                      depthMeter: 0,
                      gaEvent: 'webApplicationsTestingFunctionalTestsApiTests',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Security tests',
                      hrefTitle: 'Security tests',
                      href: 'https://hackr.io/blog/types-of-software-testing#20-security-testing',
                      depthMeter: 0,
                      gaEvent:
                        'webApplicationsTestingFunctionalTestsSecurityTests',
                    },
                  ],
                },
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Frameworks',
                depthMeter: 0,
                gaEvent: 'webApplicationsTestingFrameworks',
                child: {
                  isVisible: false,
                  itemList: [
                    {
                      level: 4,
                      isVisible: true,
                      status: 'knowledgeAbsorbed',
                      text: 'Jasmine',
                      hrefTitle: 'Jasmine',
                      href: 'https://jasmine.github.io/',
                      depthMeter: 0,
                      gaEvent: 'webApplicationsTestingFrameworksJasmine',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Karma',
                      hrefTitle: 'Karma',
                      href: 'https://karma-runner.github.io/latest/index.html',
                      depthMeter: 0,
                      gaEvent: 'webApplicationsTestingFrameworksKarma',
                    },
                  ],
                },
              },
            ],
          },
        },
        {
          level: 2,
          isVisible: false,
          status: 'knowledgeAbsorbed',
          text: 'Design and development principles',
          depthMeter: 0,
          gaEvent: 'webApplicationsDesignAndDevelopmentPrinciples',
          child: {
            isVisible: false,
            itemList: [
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'TDD - Test driven development',
                hrefTitle: 'TDD - Test driven development',
                href: 'https://www.guru99.com/test-driven-development.html',
                depthMeter: 0,
                gaEvent:
                  'webApplicationsDesignAndDevelopmentPrinciplesTddTestDrivenDevelopment',
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'DI - Dependency injection',
                hrefTitle: 'DI - Dependency injection',
                href: 'https://docs.nestjs.com/fundamentals/custom-providers',
                depthMeter: 0,
                gaEvent:
                  'webApplicationsDesignAndDevelopmentPrinciplesDiDependencyInjection',
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'SOLID',
                depthMeter: 0,
                gaEvent: 'webApplicationsDesignAndDevelopmentPrinciplesSolid',
                child: {
                  isVisible: false,
                  itemList: [
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Single responsibility',
                      hrefTitle: 'Single responsibility',
                      href: 'https://levelup.gitconnected.com/javascript-clean-code-solid-9d135f824180#3a04',
                      depthMeter: 0,
                      gaEvent:
                        'webApplicationsDesignAndDevelopmentPrinciplesSolidSingleResponsibility',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Open for extension, closed for modification',
                      hrefTitle: 'Open for extension, closed for modification',
                      href: 'https://levelup.gitconnected.com/javascript-clean-code-solid-9d135f824180#dfaf',
                      depthMeter: 0,
                      gaEvent:
                        'webApplicationsDesignAndDevelopmentPrinciplesSolidOpenForExtensionClosedForModification',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Liskov substitution',
                      hrefTitle: 'Liskov substitution',
                      href: 'https://levelup.gitconnected.com/javascript-clean-code-solid-9d135f824180#deef',
                      depthMeter: 0,
                      gaEvent:
                        'webApplicationsDesignAndDevelopmentPrinciplesSolidLiskovSubstitution',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Interface segregation',
                      hrefTitle: 'Interface segregation',
                      href: 'https://carstenbehrens.com/interface-segregation/',
                      depthMeter: 0,
                      gaEvent:
                        'webApplicationsDesignAndDevelopmentPrinciplesSolidInterfaceSegregation',
                    },
                    {
                      level: 4,
                      isVisible: false,
                      status: 'knowledgeAbsorbed',
                      text: 'Dependency inversion',
                      hrefTitle: 'Dependency inversion',
                      href: 'https://levelup.gitconnected.com/javascript-clean-code-solid-9d135f824180#c0b6',
                      depthMeter: 0,
                      gaEvent:
                        'webApplicationsDesignAndDevelopmentPrinciplesSolidDependencyInversion',
                    },
                  ],
                },
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'KISS - Keep it simple, stupid',
                hrefTitle: 'KISS - Keep it simple, stupid',
                href: 'https://deviq.com/principles/keep-it-simple',
                depthMeter: 0,
                gaEvent:
                  'webApplicationsDesignAndDevelopmentPrinciplesSolidKissKeepItSimpleStupid',
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: "YAGNI - You aren't going to need it",
                hrefTitle: "YAGNI - You aren't going to need it",
                href: 'https://martinfowler.com/bliki/Yagni.html',
                depthMeter: 0,
                gaEvent:
                  'webApplicationsDesignAndDevelopmentPrinciplesSolidYagniYouAreNotGoingToNeedIt',
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: "DRY - Don't repeat yourself",
                hrefTitle: "DRY - Don't repeat yourself",
                href: 'https://dzone.com/articles/software-design-principles-dry-and-kiss',
                depthMeter: 0,
                gaEvent:
                  'webApplicationsDesignAndDevelopmentPrinciplesSolidDryDoNotRepeatYourself',
              },
            ],
          },
        },
        {
          level: 2,
          isVisible: false,
          status: 'knowledgeAbsorbed',
          text: 'Project management',
          depthMeter: 0,
          gaEvent: 'webApplicationsProjectManagement',
          child: {
            isVisible: false,
            itemList: [
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Jira',
                hrefTitle: 'Jira',
                href: 'https://www.atlassian.com/software/jira?bundle=jira-software&edition=free',
                depthMeter: 0,
                gaEvent: 'webApplicationsProjectManagementJira',
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Scrum  (Agile methodology)',
                hrefTitle: 'Scrum  (Agile methodology)',
                href: 'https://www.wrike.com/scrum-guide/',
                depthMeter: 0,
                gaEvent:
                  'webApplicationsProjectManagementScrumAgileMethodology',
              },
            ],
          },
        },
        {
          level: 2,
          isVisible: false,
          status: 'knowledgeAbsorbed',
          text: 'SSG - Static site generators',
          depthMeter: 0,
          gaEvent: 'webApplicationsSsgStaticSiteGenerators',
          child: {
            isVisible: false,
            itemList: [
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'NuxtJS',
                hrefTitle: 'NuxtJS',
                href: 'https://nuxtjs.org/',
                depthMeter: 0,
                gaEvent: 'webApplicationsSsgStaticSiteGeneratorsNuxtJs',
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Jekyll',
                hrefTitle: 'Jekyll',
                href: 'https://jekyllrb.com/',
                depthMeter: 0,
                gaEvent: 'webApplicationsSsgStaticSiteGeneratorsJekyll',
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'VuePress',
                hrefTitle: 'VuePress',
                href: 'https://vuepress.vuejs.org/',
                depthMeter: 0,
                gaEvent: 'webApplicationsSsgStaticSiteGeneratorsVuePress',
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeNeedToGain',
                text: 'Hugo',
                hrefTitle: 'Hugo',
                href: 'https://gohugo.io/',
                depthMeter: 0,
                gaEvent: 'webApplicationsSsgStaticSiteGeneratorsHugo',
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeNeedToGain',
                text: 'Eleventy',
                hrefTitle: 'Eleventy',
                href: 'https://www.11ty.dev/',
                depthMeter: 0,
                gaEvent: 'webApplicationsSsgStaticSiteGeneratorsEleventy',
              },
            ],
          },
        },
        {
          level: 2,
          isVisible: false,
          status: 'knowledgeAbsorbed',
          text: 'E-commerce platforms',
          depthMeter: 0,
          gaEvent: 'webApplicationsEcommercePlatforms',
          child: {
            isVisible: false,
            itemList: [
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'Shopware',
                hrefTitle: 'Shopware',
                href: 'https://www.shopware.com/en/',
                depthMeter: 0,
                gaEvent: 'webApplicationsEcommercePlatformsShopware',
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeAbsorbed',
                text: 'commercetools',
                hrefTitle: 'commercetools',
                href: 'https://commercetools.com/',
                depthMeter: 0,
                gaEvent: 'webApplicationsEcommercePlatformsCommercetools',
              },
              {
                level: 3,
                isVisible: false,
                status: 'knowledgeNeedToGain',
                text: 'Pimcore',
                hrefTitle: 'Pimcore',
                href: 'https://pimcore.com/en',
                depthMeter: 0,
                gaEvent: 'webApplicationsEcommercePlatformsPimcore',
              },
            ],
          },
        },
        {
          level: 2,
          isVisible: false,
          status: 'knowledgeAbsorbed',
          text: 'Semantic versioning',
          hrefTitle: 'Semantic versioning',
          href: 'https://semver.org/',
          depthMeter: 0,
          gaEvent: 'webApplicationsSemanticVersioning',
        },
        {
          level: 2,
          isVisible: false,
          status: 'knowledgeAbsorbed',
          text: 'CI/CD - Continuous integration and continuous delivery',
          hrefTitle: 'CI/CD - Continuous integration and continuous delivery',
          href: 'https://www.infoworld.com/article/3271126/what-is-cicd-continuous-integration-and-continuous-delivery-explained.html',
          depthMeter: 0,
          gaEvent:
            'webApplicationsCiCdContinuousIntegrationAndContinuousDelivery',
        },
        {
          level: 2,
          isVisible: false,
          status: 'knowledgeAbsorbed',
          text: 'Proxy and reverse proxy',
          hrefTitle: 'Proxy and reverse proxy',
          href: 'https://medium.com/globant/understanding-nginx-as-a-reverse-proxy-564f76e856b2',
          depthMeter: 0,
          gaEvent: 'webApplicationsProxyAndReverseProxy',
        },
        {
          level: 2,
          isVisible: false,
          status: 'knowledgeAbsorbed',
          text: 'Load balancing',
          hrefTitle: 'Load balancing',
          href: 'https://www.nginx.com/resources/glossary/load-balancing/',
          depthMeter: 0,
          gaEvent: 'webApplicationsLoadBalancing',
        },
        {
          level: 2,
          isVisible: false,
          status: 'knowledgeAbsorbed',
          text: 'Docker',
          hrefTitle: 'Docker',
          href: 'https://www.docker.com/',
          depthMeter: 0,
          gaEvent: 'webApplicationsDocker',
        },
      ],
    },
  },
  {
    level: 1,
    isVisible: true,
    status: 'knowledgeAbsorbed',
    text: 'And I keep learning',
    depthMeter: 0,
    gaEvent: 'andIKeepLearning',
    child: {
      isVisible: true,
      itemList: [
        {
          level: 2,
          isVisible: false,
          status: 'knowledgeNeedToGain',
          text: 'What is going to be next?',
          depthMeter: 0,
          gaEvent: 'andIKeepLearningWhatIsGoingToBeNext',
        },
      ],
    },
  },
];
