import { RoadmapItemInterface } from '../roadmap-item/roadmap-item.interface';

export const roadmapItemList: RoadmapItemInterface[] = [
  {
    level: 1,
    status: 'knowledgeAbsorbed',
    text: 'Level 1',
    depthMeter: 0,
    isVisible: true,
    child: {
      id: '3a526d02e84c480f9716a037e380ade4',
      isVisible: true,
      itemList: [
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          hrefTitle: 'Level 2',
          href: 'https://wwww.google.com',
          text: 'Level 2 (variation 1, segment 1)',
          depthMeter: 0,
          isVisible: true,
          gaEvent: '',
        },
      ],
    },
  },
  {
    level: 1,
    status: 'knowledgeAbsorbed',
    text: 'Level 1',
    depthMeter: 0,
    isVisible: true,
    child: {
      id: '3a526d02e84c480f9716a037e380ade4',
      isVisible: false,
      itemList: [
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'Level 2 (variation 2, segment 1)',
          depthMeter: 0,
          isVisible: false,
          gaEvent: '',
          child: {
            id: '3a526d02e84c480f9716a037e380ade4',
            isVisible: false,
            itemList: [
              {
                level: 3,
                status: 'knowledgeAbsorbed',
                hrefTitle: 'Level 3',
                href: 'https://wwww.google.com',
                text: 'Level 3 (variation 1, segment 1)',
                depthMeter: 0,
                isVisible: false,
                gaEvent: '',
              },
            ],
          },
        },
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'Level 2 (variation 2, segment 2)',
          depthMeter: 0,
          isVisible: false,
          gaEvent: '',
        },
      ],
    },
  },
  {
    level: 1,
    status: 'knowledgeAbsorbed',
    text: 'Level 1',
    depthMeter: 0,
    isVisible: true,
    child: {
      id: '3a526d02e84c480f9716a037e380ade4',
      isVisible: false,
      itemList: [
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'Level 2 (variation 3, segment 1)',
          depthMeter: 0,
          isVisible: false,
          gaEvent: '',
        },
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'Level 2 (variation 3, segment 2)',
          depthMeter: 0,
          isVisible: false,
          gaEvent: '',
          child: {
            id: '3a526d02e84c480f9716a037e380ade4',
            isVisible: false,
            itemList: [
              {
                level: 3,
                status: 'knowledgeAbsorbed',
                text: 'Level 3 (variation 2, segment 1)',
                depthMeter: 0,
                isVisible: false,
                gaEvent: '',
                child: {
                  id: '3a526d02e84c480f9716a037e380ade4',
                  isVisible: false,
                  itemList: [
                    {
                      level: 4,
                      status: 'knowledgeAbsorbed',
                      hrefTitle: 'Level 4',
                      href: 'https://wwww.google.com',
                      text: 'Level 4 (variation 1, segment 1)',
                      depthMeter: 0,
                      isVisible: false,
                      gaEvent: '',
                    },
                  ],
                },
              },
              {
                level: 3,
                status: 'knowledgeAbsorbed',
                hrefTitle: 'Level 3',
                href: 'https://wwww.google.com',
                text: 'Level 3 (variation 2, segment 2)',
                depthMeter: 0,
                isVisible: false,
                gaEvent: '',
              },
            ],
          },
        },
      ],
    },
  },
  {
    level: 1,
    status: 'knowledgeAbsorbed',
    text: 'Level 1',
    depthMeter: 0,
    isVisible: true,
    child: {
      id: '3a526d02e84c480f9716a037e380ade4',
      isVisible: false,
      itemList: [
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'Level 2',
          depthMeter: 0,
          isVisible: false,
          gaEvent: '',
        },
        {
          level: 2,
          status: 'knowledgeAbsorbed',
          text: 'Level 2',
          depthMeter: 0,
          isVisible: false,
          gaEvent: '',
          child: {
            id: '3a526d02e84c480f9716a037e380ade4',
            isVisible: false,
            itemList: [
              {
                level: 3,
                status: 'knowledgeAbsorbed',
                hrefTitle: 'Level 3',
                href: 'https://wwww.google.com',
                text: 'Level 3 (variation 3, segment 1)',
                depthMeter: 0,
                isVisible: false,
                gaEvent: '',
              },
              {
                level: 3,
                status: 'knowledgeAbsorbed',
                text: 'Level 3 (variation 3, segment 2)',
                depthMeter: 0,
                isVisible: false,
                gaEvent: '',
                child: {
                  id: '3a526d02e84c480f9716a037e380ade4',
                  isVisible: false,
                  itemList: [
                    {
                      level: 4,
                      status: 'knowledgeAbsorbed',
                      text: 'Level 4 (variation 2, segment 1)',
                      depthMeter: 0,
                      isVisible: false,
                      gaEvent: '',
                      child: {
                        id: '3a526d02e84c480f9716a037e380ade4',
                        isVisible: false,
                        itemList: [
                          {
                            level: 5,
                            status: 'knowledgeAbsorbed',
                            hrefTitle: 'Level 5',
                            href: 'https://wwww.google.com',
                            text: 'Level 5 (variation 1, segment 1)',
                            depthMeter: 0,
                            isVisible: false,
                            gaEvent: '',
                          },
                        ],
                      },
                    },
                    {
                      level: 4,
                      status: 'knowledgeAbsorbed',
                      hrefTitle: 'Level 4',
                      href: 'https://wwww.google.com',
                      text: 'Level 4 (variation 2, segment 2)',
                      depthMeter: 0,
                      isVisible: false,
                      gaEvent: '',
                    },
                  ],
                },
              },
              {
                level: 3,
                status: 'knowledgeAbsorbed',
                text: 'Level 3',
                depthMeter: 0,
                isVisible: false,
                gaEvent: '',
                child: {
                  id: '3a526d02e84c480f9716a037e380ade4',
                  isVisible: false,
                  itemList: [
                    {
                      level: 4,
                      status: 'knowledgeAbsorbed',
                      hrefTitle: 'Level 4',
                      href: 'https://wwww.google.com',
                      text: 'Level 4 (variation 3, segment 1)',
                      depthMeter: 0,
                      isVisible: false,
                      gaEvent: '',
                    },
                    {
                      level: 4,
                      status: 'knowledgeAbsorbed',
                      text: 'Level 4 (variation 3, segment 2)',
                      depthMeter: 0,
                      isVisible: false,
                      gaEvent: '',
                      child: {
                        id: '3a526d02e84c480f9716a037e380ade4',
                        isVisible: false,
                        itemList: [
                          {
                            level: 5,
                            status: 'knowledgeAbsorbed',
                            hrefTitle: 'Level 5',
                            href: 'https://wwww.google.com',
                            text: 'Level 5',
                            depthMeter: 0,
                            isVisible: false,
                            gaEvent: '',
                          },
                        ],
                      },
                    },
                  ],
                },
              },
            ],
          },
        },
      ],
    },
  },
];
