import { RoadmapItemInterface } from './roadmap-item.interface';

// TODO: add Storybook

const roadmapItemList: RoadmapItemInterface[] = [
  {
    level: 1,
    status: 'knowledgeAbsorbed',
    text: 'HTML',
    version: 5,
    childList: [
      {
        level: 2,
        status: 'knowledgeAbsorbed',
        hrefTitle: 'Semantic markup',
        href: 'https://developer.mozilla.org/en-US/docs/Web/HTML/Element',
        text: 'Semantic markup',
        gaEvent: 'htmlSemanticMarkup',
      },
      {
        level: 2,
        status: 'knowledgeAbsorbed',
        hrefTitle: 'Responsive images',
        href: 'https://developers.google.com/web/fundamentals/design-and-ux/responsive/images',
        text: 'Responsive images',
        gaEvent: 'htmlResponsiveImages',
      },
      {
        level: 2,
        status: 'knowledgeAbsorbed',
        hrefTitle: 'Conventions and best practices',
        href: 'https://github.com/hail2u/html-best-practices',
        text: 'Conventions and best practices',
        gaEvent: 'htmlConventionsAndBestPractices',
      },
      {
        level: 2,
        status: 'knowledgeAbsorbed',
        hrefTitle: 'SEO',
        href: 'https://developers.google.com/search/docs',
        text: 'SEO',
        gaEvent: 'htmlSEO',
      },
      {
        level: 2,
        status: 'knowledgeAbsorbed',
        hrefTitle: 'Accessibility',
        href: 'https://www.smashingmagazine.com/2021/03/complete-guide-accessible-front-end-components/',
        text: 'Accessibility',
        gaEvent: 'htmlAccessibility',
      },
    ],
  },
  {
    level: 1,
    status: 'knowledgeAbsorbed',
    text: 'CSS',
    version: 3,
    childList: [
      {
        level: 2,
        status: 'knowledgeAbsorbed',
        hrefTitle: 'Specificity',
        href: 'https://specifishity.com/',
        text: 'Specificity',
        gaEvent: 'cssSpecificity',
      },
      {
        level: 2,
        status: 'knowledgeAbsorbed',
        text: 'Frameworks',
        childList: [
          {
            level: 3,
            status: 'knowledgeAbsorbed',
            text: 'Based on CSS first',
            childList: [
              {
                level: 4,
                status: 'knowledgeAbsorbed',
                hrefTitle: 'Foundation',
                href: 'https://get.foundation/',
                text: 'Foundation',
                gaEvent: 'cssFrameworksFoundation',
              },
              {
                level: 4,
                status: 'knowledgeAbsorbed',
                hrefTitle: 'Bootstrap',
                href: 'https://getbootstrap.com/',
                text: 'Bootstrap',
                gaEvent: 'cssFrameworksBootstrap',
              },
              {
                level: 4,
                status: 'knowledgeAbsorbed',
                hrefTitle: 'Tailwind',
                href: 'https://tailwindcss.com/',
                text: 'Tailwind',
                gaEvent: 'cssFrameworksTailwind',
              },
            ],
          },
          {
            level: 3,
            status: 'knowledgeAbsorbed',
            text: 'JavaScript based',
            childList: [
              {
                level: 4,
                status: 'knowledgeAbsorbed',
                hrefTitle: 'Chakra UI',
                href: 'https://chakra-ui.com/',
                text: 'Chakra UI',
                gaEvent: 'cssFrameworksChakraUI',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    level: 1,
    status: 'knowledgeAbsorbed',
    text: 'JavaScript',
    version: 'ES6+',
    childList: [
      {
        level: 2,
        status: 'knowledgeAbsorbed',
        hrefTitle: 'DOM manipulation',
        href: 'https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Manipulating_documents',
        text: 'DOM manipulation',
        gaEvent: 'javaScriptDOMmanipulation',
      },
      {
        level: 2,
        status: 'knowledgeAbsorbed',
        hrefTitle: 'Modules',
        href: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules',
        text: 'Modules',
        gaEvent: 'javaScriptModules',
      },
      {
        level: 2,
        status: 'knowledgeAbsorbed',
        text: 'Frameworks and libraries',
        childList: [
          {
            level: 3,
            status: 'knowledgeAbsorbed',
            hrefTitle: 'Angular',
            href: 'https://angular.io/',
            text: 'Angular',
            gaEvent: 'javaScriptFrameworksAndLibrariesAngular',
            childList: [
              {
                level: 4,
                status: 'knowledgeAbsorbed',
                hrefTitle: 'RxJS',
                href: 'https://rxjs.dev/',
                text: 'RxJS',
                gaEvent: 'javaScriptFrameworksAndLibrariesRxJS',
              },
              {
                level: 4,
                status: 'knowledgeNeedToGain',
                hrefTitle: 'NgRx',
                href: 'https://ngrx.io/',
                text: 'NgRx',
                gaEvent: 'javaScriptFrameworksAndLibrariesNgRx',
              },
            ],
          },
          {
            level: 3,
            status: 'knowledgeAbsorbed',
            hrefTitle: 'React',
            href: 'https://reactjs.org/',
            text: 'React',
            gaEvent: 'javaScriptFrameworksAndLibrariesReact',
          },
          {
            level: 3,
            status: 'knowledgeAbsorbed',
            hrefTitle: 'Vue.js',
            href: 'https://vuejs.org/',
            text: 'Vue.js',
            gaEvent: 'javaScriptFrameworksAndLibrariesVueJs',
            childList: [
              {
                level: 4,
                status: 'knowledgeAbsorbed',
                hrefTitle: 'Vuex',
                href: 'https://vuex.vuejs.org/',
                text: 'Vuex',
                gaEvent: 'javaScriptFrameworksAndLibrariesVuex',
              },
            ],
          },
          {
            level: 3,
            status: 'knowledgeNeedToGain',
            hrefTitle: 'Svelte',
            href: 'https://svelte.dev/',
            text: 'Svelte',
            gaEvent: 'javaScriptFrameworksAndLibrariesSvelte',
          },
        ],
      },
    ],
  },
  {
    level: 1,
    status: 'knowledgeAbsorbed',
    text: 'Web security',
    childList: [
      {
        level: 2,
        status: 'knowledgeAbsorbed',
        hrefTitle: 'Hypertext transfer protocol secure (HTTPS)',
        href: 'https://www.cloudflare.com/en-gb/learning/ssl/why-is-http-not-secure/',
        text: 'Hypertext transfer protocol secure (HTTPS)',
        gaEvent: 'webSecurityHTTPS',
      },
      {
        level: 2,
        status: 'knowledgeAbsorbed',
        hrefTitle: 'Cross-origin resource sharing (CORS)',
        href: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS',
        text: 'Cross-origin resource sharing (CORS)',
        gaEvent: 'webSecurityCORS',
      },
      // TODO: figure out
      // {
      //   level: 2,
      //   status: 'knowledgeAbsorbed',
      //   hrefTitle: 'Content security policy (CSP)',
      //   href: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP',
      //   text: 'Content security policy (CSP)',
      //   gaEvent: 'webSecurityCSP',
      // },
      {
        level: 2,
        status: 'knowledgeAbsorbed',
        hrefTitle: 'Top 10 OWASP security risks',
        href: 'https://owasp.org/www-project-top-ten/',
        text: 'Top 10 OWASP security risks',
        gaEvent: 'webSecurityTop10OWASPsecurityRisks',
      },
    ],
  },
  {
    level: 1,
    status: 'knowledgeAbsorbed',
    text: 'Version control systems',
    childList: [
      {
        level: 2,
        status: 'knowledgeAbsorbed',
        hrefTitle: 'Git',
        href: 'https://git-scm.com/',
        text: 'Git',
        gaEvent: 'versionControlSystemsGit',
      },
      {
        level: 2,
        status: 'knowledgeAbsorbed',
        text: 'Code hosting platforms',
        childList: [
          {
            level: 3,
            status: 'knowledgeAbsorbed',
            hrefTitle: 'GitHub',
            href: 'https://github.com/',
            text: 'GitHub',
            gaEvent: 'versionControlSystemsGitHub',
          },
          {
            level: 3,
            status: 'knowledgeAbsorbed',
            hrefTitle: 'GitLab',
            href: 'https://about.gitlab.com/',
            text: 'GitLab',
            gaEvent: 'versionControlSystemsGitLab',
          },
          {
            level: 3,
            status: 'knowledgeAbsorbed',
            hrefTitle: 'Bitbucket',
            href: 'https://bitbucket.org/',
            text: 'Bitbucket',
            gaEvent: 'versionControlSystemsBitbucket',
          },
        ],
      },
    ],
  },
  {
    level: 1,
    status: 'knowledgeAbsorbed',
    text: 'Package managers',
    childList: [
      {
        level: 2,
        status: 'knowledgeAbsorbed',
        hrefTitle: 'yarn',
        href: 'https://yarnpkg.com/',
        text: 'yarn',
        gaEvent: 'packageManagersYarn',
      },
      {
        level: 2,
        status: 'knowledgeAbsorbed',
        hrefTitle: 'npm',
        href: 'https://www.npmjs.com/',
        text: 'npm',
        gaEvent: 'packageManagersNpm',
      },
    ],
  },
  {
    level: 1,
    status: 'knowledgeAbsorbed',
    text: 'Application authentication and authorization',
    // TODO: childList: [] e.g. openId, keycloak
  },
  {
    level: 1,
    status: 'knowledgeAbsorbed',
    text: 'Application testing',
    childList: [
      {
        level: 2,
        status: 'knowledgeAbsorbed',
        text: 'Functional tests',
        childList: [
          {
            level: 3,
            status: 'knowledgeAbsorbed',
            hrefTitle: 'Unit test',
            href: 'https://www.guru99.com/unit-testing-guide.html',
            text: 'Unit test',
            gaEvent: 'ApplicationTestingUnitTest',
          },
          {
            level: 3,
            status: 'knowledgeNeedToGain',
            hrefTitle: 'Integration test',
            href: 'https://www.guru99.com/integration-testing.html',
            text: 'Integration test',
            gaEvent: 'ApplicationTestingIntegrationTest',
          },
        ],
      },
      {
        level: 2,
        status: 'knowledgeAbsorbed',
        text: 'Frameworks',
        childList: [
          {
            level: 3,
            status: 'knowledgeAbsorbed',
            hrefTitle: 'Jasmine',
            href: 'https://jasmine.github.io/',
            text: 'Jasmine',
            gaEvent: 'ApplicationTestingFrameworksJasmine',
          },
          {
            level: 3,
            status: 'knowledgeAbsorbed',
            hrefTitle: 'Karma',
            href: 'https://karma-runner.github.io/latest/index.html',
            text: 'Karma',
            gaEvent: 'ApplicationTestingFrameworksKarma',
          },
        ],
      },
    ],
  },
  {
    level: 1,
    status: 'knowledgeAbsorbed',
    text: 'Static site generators',
    childList: [
      {
        level: 2,
        status: 'knowledgeAbsorbed',
        hrefTitle: 'NuxtJS',
        href: 'https://nuxtjs.org/',
        text: 'NuxtJS',
        gaEvent: 'staticSiteGeneratorsNuxtJS',
      },
      {
        level: 2,
        status: 'knowledgeAbsorbed',
        hrefTitle: 'Jekyll',
        href: 'https://jekyllrb.com/',
        text: 'Jekyll',
        gaEvent: 'staticSiteGeneratorsJekyll',
      },
      {
        level: 2,
        status: 'knowledgeAbsorbed',
        hrefTitle: 'VuePress',
        href: 'https://vuepress.vuejs.org/',
        text: 'VuePress',
        gaEvent: 'staticSiteGeneratorsVuePress',
      },
      {
        level: 2,
        status: 'knowledgeNeedToGain',
        hrefTitle: 'Hugo',
        href: 'https://gohugo.io/',
        text: 'Hugo',
        gaEvent: 'staticSiteGeneratorsHugo',
      },
      {
        level: 2,
        status: 'knowledgeNeedToGain',
        hrefTitle: 'Eleventy',
        href: 'https://www.11ty.dev/',
        text: 'Eleventy',
        gaEvent: 'staticSiteGeneratorsEleventy',
      },
    ],
  },
  {
    level: 1,
    status: 'knowledgeAbsorbed',
    text: 'Application versioning',
    childList: [
      {
        level: 2,
        status: 'knowledgeAbsorbed',
        hrefTitle: 'Semantic versioning',
        href: 'https://semver.org/',
        text: 'Semantic versioning',
        gaEvent: 'applicationVersioningSemanticVersioning',
      },
    ],
  },
  {
    level: 1,
    status: 'knowledgeAbsorbed',
    text: 'Virtualization',
    childList: [
      {
        level: 2,
        status: 'knowledgeAbsorbed',
        hrefTitle: 'Docker',
        href: 'https://www.docker.com/',
        text: 'Docker',
        gaEvent: 'virtualizationDocker',
      },
    ],
  },
  {
    level: 1,
    status: 'knowledgeNeedToGain',
    text: 'And I keep learning',
    childList: [
      {
        level: 2,
        status: 'knowledgeNeedToGain',
        text: '...',
      },
    ],
  },
];

export default roadmapItemList;
