name: Karma tests

# Run on every push
on: [ push ]

# Job setup
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checkout repository
      - uses: actions/setup-node@v1 # Setup node
        with:
          node-version: '12'
      - name: Run Karma tests
        run: |
          npm install yarn -g
          yarn install
          yarn test
